/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.board;

public class AppTest {
  // 지우라고 하셨지만 일단 주석처리
  //    @Test public void appHasAGreeting() {
  //        //App classUnderTest = new App();
  //        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  //    }
}
